version: '3.8'

services:
  app:
    image: ghcr.io/guanhongming/uc-public:app
    container_name: app
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./app-code:/var/www/html
    env_file:
      - .env

  webserver:
    image: ghcr.io/guanhongming/uc-public:web 
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./app-code:/var/www/html:ro
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
